#!/bin/bash

# compile
gcc \
	openarmor.c \
	json.c \
	$(pkg-config --libs --cflags libcurl) \
	$(pkg-config --libs --cflags json-c) \
	-o openarmor \
	-Wall

# check for run flag
if [[ $* == *--and-run* ]];
then
	# run openarmor
	./openarmor

	# insert a newline
	echo ""
fi