#!/bin/bash

# compile
gcc \
    openarmor.c \
    api.c \
    functions.c \
    map_lib.c \
    $(pkg-config --libs --cflags libcurl) \
    $(pkg-config --libs --cflags json-c) \
    -o openarmor \
    -Wall

# check for run flag
if [[ $* == *--and-run* ]];
then
    # run openarmor
    ./openarmor

    # insert a newline
    echo ""
fi