<!doctype html>
<html>
<head>
    <title>OpenArmor.org</title>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="http://cdn.tierlabs.com/global/jquery/jquery.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

    <link rel="SHORTCUT ICON" href="/images/fav.png">

    <style>
        body {
            font-family: 'Raleway', sans-serif;
            font-size: 18px;
            line-height: 28px;
        }

        a:link, a:visited, a:active {
            color: #309919;
        }

        a:hover {
            text-decoration: none;
            color: #999 !important;
        }

        .container {
            max-width: 1400px;
            width: auto;
        }

        .black_stuff {
            color: #fff;
        }

        h1, h2, h3, h4, h5, h6 {
            margin-top: 0;
            font-family: 'Raleway', sans-serif;
        }

        .menu_set {
            display: block;
            text-align: right;
        }

        .menu_set > a {
            display: inline-block;
            padding: 16px 20px;
            color: #9DFF86;
            font-size: 16px;
        }

        .menu_set > a:hover {
            text-decoration: none;
            color: #fff !important;
        }

        .green {
            color: #64FF40;
        }

        .left {
            text-align: left;
        }

        .center {
            text-align: center;
        }

        .right {
            text-align: right;
        }
    </style>
</head>
<body>
<div style="display: block; background: #1F1F1F; padding: 40px;">
    <div class="container black_stuff">
        <div class="row">
            <div class="col-md-6">
                <h1 style="font-size: 46px;"><i class="fa fa-shield"></i> OpenArmor</h1>
            </div>
            <div class="col-md-6 right">
                <div class="menu_set">
                    <a href="/"><i class="fa fa-home"></i> Home</a>
                    <a href="#/about"><i class="fa fa-question"></i> About</a>
                    <a href="#/resources"><i class="fa fa-book"></i> Resources</a>
                    <a href="#/tools"><i class="fa fa-wrench"></i> Tools</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="display: block; background: #0e0e0e; padding: 40px;">
    <div class="container black_stuff">
        <div class="row">
            <div class="col-md-12 center">
                <h3><i class="fa fa-wrench"></i> Your tool against:</h3>
                <h5 style="line-height: 28px;">
                    <i class="fa fa-check green"></i> Digital Tyranny &bull;
                    <i class="fa fa-check green"></i> Surveillance &bull;
                    <i class="fa fa-check green"></i> Free Speech Interferance &bull;
                    <i class="fa fa-check green"></i> Privacy Violations
                </h5>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row" style="margin-top: 40px;">
        <div class="col-md-4" style="margin-bottom: 40px;">
            <h2><i class="fa fa-shield"></i> What is OpenArmor?</h2>
            OpenArmor is a Florida based non-profit organization dedicated to providing <a href="/education">educational resources</a> on issues
            such as security and encryption. In addition to educational resources, OpenArmor also provides <a href="/tools">tools made in-house
                as well as tools from third parties</a> to help put what you've learned into practice and help you
            to communicate, share, store, and distribute anonymously and/or securely. While absolute privacy and
            security is usually not practical, our tools will <strong style="text-decoration: underline;">severely cripple</strong> the
            efforts of attackers whether they are a crook, hacker, or <a href="http://en.wikipedia.org/wiki/PRISM_(surveillance_program)" target="_blank">your own government</a>.
        </div>
        <div class="col-md-4" style="margin-bottom: 40px;">
            <h2><i class="fa fa-question"></i> Why should I care?</h2>
            As technology expands and the personal lives of virtually everybody moves online to some degree, the pool of surveillable targets
            grows at an <strong style="text-decoration: underline;">exponentially increasing rate</strong>. This is the perfect setup for unlawful <a href="http://en.wikipedia.org/wiki/PRISM_(surveillance_program)" target="_blank">mass data collection</a> and the surveillance
            of innocent civilians without cause under the guise of "security" or another purpose which would then be used to lead you
            to believe that being surveilled is in your best interest. The worst part of it all is that it's happening without your
            knowledge and/or in cooperation with organizations you trust who <a href="http://en.wikipedia.org/wiki/National_security_letter" target="_blank">are required by law to keep quiet</a>.
        </div>
        <div class="col-md-4" style="margin-bottom: 40px;">
            <h2><i class="fa fa-gavel"></i> Is OpenArmor legal?</h2>
            In the United States of America, absolutely! In other countries, it depends. As Americans, you are guaranteed certain rights under the <a href="http://en.wikipedia.org/wiki/United_States_Constitution" target="_blank">United States Constitution</a>.
            Of those, OpenArmor deals primarily with your 1st Amendment right to Freedom of Speech and your 4th Amendment right prohibiting
            unreasonable searches and seizures. Now, this does not mean the United States Constitution is followed absolutely, which is,
            of course, why OpenArmor must exist in the first place. One thing is for sure: Constitution or not, OpenArmor will help protect you.
        </div>
    </div>
</div>
<div style="display: block; background: #1F1F1F; padding: 40px;">
    <div class="container black_stuff">
        <div class="row">
            <div class="col-md-12 center">
                <h2>"The NSA has built an infrastructure that allows it to intercept almost everything. With this capability, the vast majority of human communications are automatically ingested without targeting..."</h2>
                <small>- Edward Snowden -</small>
            </div>
        </div>
    </div>
</div>
</body>
</html>